### ISSUE TITLE
The InvalidPathException during IDE start (Aqua IDE)

### ISSUE THREAD

**Issue by rabestro** [xonixx/intellij-awk#170]
ava.nio.file.InvalidPathException: Illegal char <|> at index 31: intellij_awk.psi.awkuservarname|declinit
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.resolve(Path.java:515)
	at com.intellij.util.indexing.IndexInfrastructure.getIndexDirectory(IndexInfrastructure.java:62)
	at com.intellij.util.indexing.IndexInfrastructure.getIndexDirectory(IndexInfrastructure.java:53)
	at com.intellij.util.indexing.IndexInfrastructure.getIndexDirectory(IndexInfrastructure.java:49)
	at com.intellij.util.indexing.IndexInfrastructure.getIndexRootDir(IndexInfrastructure.java:35)
	at com.intellij.util.indexing.diagnostic.StorageDiagnosticData.indexStorageStatistics(StorageDiagnosticData.kt:138)
	at com.intellij.util.indexing.diagnostic.StorageDiagnosticData.getStorageDataStatistics(StorageDiagnosticData.kt:96)
	at com.intellij.util.indexing.diagnostic.StorageDiagnosticData.dump(StorageDiagnosticData.kt:71)
	at com.intellij.util.indexing.diagnostic.StorageDiagnosticData.dumpPeriodically$lambda$0(StorageDiagnosticData.kt:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by rabestro** [comment]
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/52966251/226633113-a4110d32-3418-4782-9a3b-80ad5ba68af3.png">

**Comment by xonixx** [comment]
Thank you for the bug report. Looks like I know the source of the issue. I hope to release a fix soon.

**Comment by xonixx** [comment]
https://youtrack.jetbrains.com/issue/IDEA-316275/The-InvalidPathException-during-IDE-start
